travis:
  secure:
    BINSTAR_TOKEN: D84Jie/joUZTUXYsN81RESXdgpFEqNSc36M7yN5QnsbPeF3XXehR0XSc6TKA1liKl7etDISLOk86hBSaR4UtEgIwmFHXY8/wbuzn6O2QimtYrQ4XFghWb/TCTttokxPy7RiyKG0u+fLZi6DNAY8zBLEquZtPpLOpX62FKmd4NI24h3Q85hEbCQGtoq3rUwuUIVUH/NuUJy8OqbpK7TfJnh/lGZLFcULMvuqDe4wCz0BJaEwylKJ02X5FYlYKZs38vXB4qIpspxL93Elw+BNAw9HznlMKGvPU8OfAPZ9FqrqiPWp5P5m/K8qh6Mce+ZRFkvblhSv7YHBo/CRe1ROaqxTTsZeHn+7Swt92N7ikI2UVaQKIQOPVd9tQgcL63fbFZk8cLTxrBNUvarKHmfozDpCuT36xk1D3gSii54u86Gv6luUfmp3q5vDvQYIzePM7bE0sXJgwUV6dSplg/PeDTfy83T9JkxwBhOnw9mTqEKZJF7yKo9yGINqBd3rv7Jn26IApumhTEbXhL/ksAvjdQ9IQecjPELsPiRWU749Bmyo7ilUP2pPTql+NErSG0UXqZdUcH/bsVauhFKZZWT4mMVzoTdmXDnsQEU1tNMFZpM6bFarGXbnH7BBZMZBBXEwRPneNtxkl1MZzSQSxEKh4dzSP6AIYY2G9nICL/ILk5hQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
